package com.woniu.pojo;
// Generated 2019-12-17 16:29:24 by Hibernate Tools 5.4.7.Final

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private Integer did;
	private String dname;
	private String dloc;

	public Dept() {
	}

	public Dept(String dname, String dloc) {
		this.dname = dname;
		this.dloc = dloc;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public String getDloc() {
		return this.dloc;
	}

	public void setDloc(String dloc) {
		this.dloc = dloc;
	}

}
